version: "3.3"
services:
  app:
    build: .
    restart: always
    environment:
      - VERSION=1.1.4
    image: boristax/wardrobes:v1.1.4
    ports:
      - "5555:5555"
    command: npm run start
    volumes: 
      - wardrobes-db:/app/src/server/database
volumes:
  wardrobes-db:
      external: true